version: "3"

networks:
  todo-app-network:

services:
  db:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: mysql_test
      MYSQL_ROOT_PASSWORD: root
    networks:
      - todo-app-network
    restart: always
